import {
  Box,
  Button,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  Flex,
  Heading,
  Icon,
  Image,
  SimpleGrid,
  Text,
} from "@chakra-ui/react";

import { FaPlus } from "react-icons/fa";
import Head from "next/head";
import { Inter } from "@next/font/google";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Register() {
  const [products, setProducts] = useState([
    {
      name: "Sambal",
      price: 10,
      description:
        "Sambal is a spicy condiment made from a paste of ground chilies, shallots, garlic, and other seasonings. It is a staple condiment in Indonesian, Malaysian, Singaporean, and Bruneian cuisine.",
      image:
        "https://www.thespruceeats.com/thmb/bMRK43OmjlFaL5jRQKaiCxSkWyU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/malaysian-sambal-sauce-3030364-hero-02-abcaaf29182f43ac9938cdcb39272c82.jpg",
    },
    {
      name: "Kuey Teow",
      price: 10,
      description:
        "Kuey teow is a flat rice noodle dish that is popular in Southeast Asia. It is a staple food in Malaysia, Singapore, Indonesia, Brunei, and southern Thailand. It is also popular in the southern Chinese provinces of Guangdong, Fujian, and Hainan.",
      image:
        "https://rasamalaysia.com/wp-content/uploads/2009/11/char-koay-teow-thumb.jpg",
    },
  ]);

  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        justifyContent={"center"}
        alignItems={"center"}
        width={"100%"}
        padding={12}
        flexDirection={"column"}
      >
        <Heading className={inter.className} mb={7}>
          Products
        </Heading>
        <SimpleGrid
          spacing={4}
          templateColumns="repeat(auto-fill, minmax(250px, 1fr))"
          justifyItems={"center"}
        >
          {products.map((product) => (
            <Card key={product.name} width={"100%"}>
              <CardHeader
                display={"flex"}
                justifyContent={"space-between"}
                flexDirection={"row"}
                mb={-4}
              >
                <Heading size="md">{product.name}</Heading>
                <Text>RM {product.price}</Text>
              </CardHeader>
              <CardBody>
                <Text mb={8}>
                  {product.description.substring(0, 100) + "..."}
                </Text>
                <Image
                  borderRadius={10}
                  src={product.image}
                  width={300}
                  maxWidth={"90%"}
                  alt="product"
                  textAlign={"center"}
                />
              </CardBody>
              <CardFooter>
                <Button>View here</Button>
              </CardFooter>
            </Card>
          ))}
        </SimpleGrid>
        <Flex
          flexWrap={"wrap"}
          justifyContent={"center"}
          alignItems={"flex-start"}
        >
          {products.map((product) => (
            <Box
              key={product.name}
              //   boxShadow={"2xl"}
              padding={6}
              margin={4}
              borderRadius={12}
              width={350}
              shadow="md"
              display={"flex"}
              flexDirection={"column"}
              alignItems={"center"}
              boxShadow={"0 0 6px rgba(0, 0, 0, 0.15)"}
            >
              <Flex justifyContent={"space-between"} width={"100%"}>
                <Text fontSize={"1.5rem"} mb={4}>
                  {product.name}
                </Text>
                <Text fontSize={"1.2rem"} mb={4} ml={4}>
                  RM {product.price}
                </Text>
              </Flex>
              <Text mb={5}>{product.description}</Text>
              <Image borderRadius={10} src={product.image} alt="product" />
            </Box>
          ))}
          <Box
            //   boxShadow={"2xl"}
            padding={6}
            margin={4}
            borderRadius={12}
            width={350}
            shadow="md"
            display={"flex"}
            flexDirection={"column"}
            alignItems={"center"}
            boxShadow={"0 0 6px rgba(0, 0, 0, 0.15)"}
          >
            <Icon as={FaPlus} fontSize={"2rem"} mb={4} />
          </Box>
        </Flex>
      </Flex>
    </>
  );
}
