import {
  Box,
  Button,
  Flex,
  FormControl,
  FormHelperText,
  FormLabel,
  Heading,
  Input,
  Select,
  Text,
  Textarea,
  VStack,
} from "@chakra-ui/react";

import Head from "next/head";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Register() {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        minH={"100vh"}
        justifyContent={"center"}
        alignItems={"center"}
        width={"100%"}
      >
        <Box
          //   maxW={"100%"}
          display={"flex"}
          justifyContent="center"
          alignItems={"center"}
          margin={"auto"}
          flexDirection={"column"}
          boxShadow={"2xl"}
          padding={12}
        >
          <Heading
            color={"#0067b1"}
            as={"h2"}
            className={inter.className}
            fontSize="4xl"
            mb={4}
          >
            Registration
          </Heading>
          <VStack width={400} spacing={4} maxWidth={"100%"}>
            <FormControl>
              <FormLabel>Business Name</FormLabel>
              <Input type="name" />
              <FormHelperText>Give your store a cool name.</FormHelperText>
            </FormControl>{" "}
            <FormControl>
              <FormLabel>Description</FormLabel>
              <Textarea name="description" />
              <FormHelperText>
                What do you do? What sets you apart?
              </FormHelperText>
            </FormControl>{" "}
            <FormControl>
              <FormLabel>What do you sell?</FormLabel>
              <Select variant={"filled"}>
                <option value="Food">Food</option>
                <option value="Services">Services</option>
              </Select>
            </FormControl>{" "}
          </VStack>
          <Button variant={"solid"} colorScheme={"purple"} mt={6}>
            <Text color={"white"}>Proceed</Text>
          </Button>
        </Box>
      </Flex>
    </>
  );
}
